#include <iostream>
#include <cstdlib>
#include <sstream>
using std::string;
using std::stringstream;
using std::cout;
using std::cin;
using std::clog;
using std::endl;
using std::ostream;
using std::exception;
